const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path'),fs=require('node:fs/promises');
const {spawn,execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),python=path.join(root,'runtime','python.exe');
const data=path.join(root,'.qa','media-sync-'+Date.now()),base='http://127.0.0.1:8904';
const sample='C:/Users/Lu/Desktop/爱情公寓.mp4';
let browser,child;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label){for(let i=0;i<160;i++){if(await fn())return;await delay(100)}throw Error('Timed out: '+label)}
function wav(seconds=12){const rate=8000,n=seconds*rate,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);return b}
(async()=>{
 child=spawn(python,['-X','utf8','run.py','--no-browser','--port','8904','--data-dir',data],{cwd:root,windowsHide:true,stdio:'ignore'});
 await until(async()=>{try{return(await(await fetch(base+'/api/health')).json()).data_dir===data}catch{return false}},'isolated server');
 browser=await chromium.launch({channel:'msedge',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),errors=[];
 context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 const library=async()=>(await context.request.get(base+'/api/library')).json(),state=async()=>(await context.request.get(base+'/api/state')).json();
 const send=async(url,payload,method='POST')=>{const lib=await library(),r=await context.request.fetch(base+url,{method,data:payload,headers:{'X-CSRF-Token':lib.csrf_token}});assert(r.ok(),await r.text());return r.json()};
 const upload=async(name,buffer,mimeType)=>{const lib=await library(),r=await context.request.post(base+'/api/scripts/script-08/media',{multipart:{file:{name,mimeType,buffer}},headers:{'X-CSRF-Token':lib.csrf_token},timeout:120000});assert(r.ok(),await r.text());return r.json()};
 const linked=await upload('爱情公寓.mp4',await fs.readFile(sample),'video/mp4');
 const mediaPath=linked.media.path;
 const range=await context.request.get(base+mediaPath,{headers:{Range:'bytes=0-1023'}});assert.equal(range.status(),206);assert.equal((await range.body()).length,1024);
 const metadataPage=await context.newPage();await metadataPage.goto(base+'/script/script-08/media');
 await metadataPage.waitForFunction(()=>{const v=document.querySelector('#media-player');return v&&v.readyState>=1});
 const metadata=await metadataPage.locator('#media-player').evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight}));assert(metadata.duration>0&&metadata.width>0);
 await metadataPage.locator('#media-player').evaluate(async v=>{v.muted=true;await v.play()});await until(async()=>await metadataPage.locator('#media-player').evaluate(v=>v.currentTime)>.2,'sample decoded and playing');
 await metadataPage.locator('#media-player').evaluate(v=>{v.pause();v.currentTime=Math.min(10,v.duration/2)});await until(async()=>await metadataPage.locator('#media-player').evaluate(v=>v.readyState>=2&&!v.seeking),'sample seek decodes');
 await metadataPage.close();
 const script=await upload('pause-cue-test.wav',wav(),'audio/wav'),texts=script.blocks.filter(b=>b.kind==='text'),pic=script.blocks.find(b=>b.kind==='image');
 const blocks=[texts[0]||script.blocks[0],texts[1]||script.blocks[1],pic||script.blocks[2]];
 await send('/api/scripts/script-08/media/cues',{duration:12,cues:blocks.map((b,i)=>({id:'cue-'+i,at:[1,3,6][i],label:'暂停点'+i,block_ids:[b.id]}))},'PUT');
 const page=await context.newPage();await page.goto(base+'/control?script=script-08&body=media');
 const ready=()=>page.waitForFunction(()=>!document.querySelector('#apply-display').disabled);await ready();
 const frame=page.frames().find(f=>f.url().includes('preview=1'));await frame.locator('.wb-media-player').waitFor();
 const media=f=>f.locator('audio,video').first();
 const play=async f=>{await f.locator('.wb-media-player').hover();await f.locator('[data-media-action="play"]').click();};
 const status=f=>media(f).evaluate(v=>({position:v.currentTime,paused:v.paused,muted:v.muted}));
 const seek=async(f,value)=>{await f.locator('.wb-media-player').hover();const range=f.locator('.wb-media-progress');await range.fill(String(value));await range.dispatchEvent('input');await range.dispatchEvent('change');};
 const cuePause=async(f,at)=>until(async()=>{const v=await status(f);return v.paused&&Math.abs(v.position-at)<.13},'pause at '+at);
 console.log('sample decoded; preview ready');const baseline=await state();await play(frame);await cuePause(frame,1);await play(frame);await cuePause(frame,3);
 assert.equal((await state()).revision,baseline.revision,'confirmation preview never publishes');
 await page.locator('#apply-display').click();await until(async()=> (await state()).snapshot?.layout?.body_mode==='media','apply media');
 console.log('confirmation cue and apply passed');let applied=await state();assert(!applied.playing);assert(Math.abs(applied.media_state.position-3)<.13);
 const audience=await context.newPage();await audience.goto(base+'/display');await media(audience).waitFor({state:'attached'});await cuePause(audience,3);
 await page.bringToFront();await page.locator('.live-details').evaluate(e=>e.open=true);await page.locator('#live-play').click();await cuePause(audience,6);
 await until(async()=>{const s=await state();return !s.playing&&s.media_state.cue_id==='cue-2'},'audience cue persisted');
 if(pic)assert(await audience.locator('.wb-media-caption-scroll img').count(),'image cue shown');
 console.log('audience autonomous cue passed');await page.locator('#preview-feedback-mode').selectOption('realtime');await until(async()=> (await state()).revision>applied.revision+1,'realtime binding');await delay(350);
 await seek(frame,0);await cuePause(frame,0);await delay(350);await play(frame);await cuePause(frame,1);await cuePause(audience,1);
 await until(async()=>!(await state()).playing,'realtime cue saved');
 assert((await status(frame)).muted);assert(!(await status(audience)).muted,'audience owns sound');
 console.log('realtime cue passed');await seek(frame,7.2);await delay(350);await play(frame);await until(async()=> (await status(frame)).position>7.8,'media advances before pause');
 const beforePause=(await status(frame)).position;await page.locator('#live-pause').click();await delay(350);assert((await status(frame)).position>=beforePause-.35,'live pause must not restore old checkpoint');
 await audience.close();await play(frame);await frame.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,get:()=> 'hidden'});document.dispatchEvent(new Event('visibilitychange'))});await delay(950);
 const hiddenPosition=(await status(frame)).position;await frame.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,get:()=> 'visible'});document.dispatchEvent(new Event('visibilitychange'))});await delay(1000);
 assert((await status(frame)).position>=hiddenPosition-.2,'without audience, returning preview keeps actual media position');await play(frame);
 const audience2=await context.newPage();await audience2.goto(base+'/display');await page.bringToFront();
 const liveBefore=await state();await page.locator('#layout-media-caption').selectOption('manual');await ready();await until(async()=> (await state()).snapshot?.layout?.media_caption_mode==='manual','manual mode applied');
 await seek(frame,0);await delay(350);await frame.locator('.wb-media-player').hover();for(let i=0;i<2;i++){if(await frame.locator('[data-media-action="previous-caption"]').isEnabled()){await frame.locator('[data-media-action="previous-caption"]').click();await delay(200)}}await frame.locator('[data-media-action="next-caption"]').click();await delay(350);
 const chosen=(await state()).media_state.caption_index;await play(frame);await cuePause(frame,1);await until(async()=>!(await state()).playing,'manual cue pause saved');assert.equal((await state()).media_state.caption_index,chosen,'manual caption stays selected at cue');
 await page.locator('[data-orientation="landscape"]').click();await ready();await frame.locator('.display-stage.landscape.body-media').waitFor();
 const split=()=>frame.locator('.wb-media-player').evaluate(e=>{const m=e.querySelector('.wb-media-visual').getBoundingClientRect(),c=e.querySelector('.wb-media-caption-scroll').getBoundingClientRect();return {mediaX:m.x,captionX:c.x}});
 let side=await split();assert(side.mediaX<side.captionX,'landscape media on left');
 await page.locator('#layout-media-side').selectOption('right');await ready();await until(async()=>{const b=await split();return b.mediaX>b.captionX},'landscape swap');
 await fs.mkdir(path.join(root,'.qa/browser'),{recursive:true});await page.locator('.preview-panel').screenshot({path:path.join(root,'.qa/browser/media-landscape.png')});
 await page.locator('[data-orientation="portrait"]').click();await ready();await page.locator('.preview-panel').screenshot({path:path.join(root,'.qa/browser/media-portrait.png')});
 await page.locator('#preview-feedback-mode').selectOption('confirm');const settled=await state();
 await page.locator('#control-script').selectOption('script-01');await ready();assert.equal(await page.locator('#layout-body-mode').inputValue(),'pages');assert(await page.locator('#media-mode-option').evaluate(e=>e.disabled),'unlinked media option disabled: '+await page.locator('#media-mode-option').evaluate(e=>e.outerHTML));assert.equal((await state()).revision,settled.revision,'unlinked selection remains draft');
 await audience2.reload();await until(async()=>!(await state()).playing,'refresh pauses');assert.equal((await state()).snapshot.id,settled.snapshot.id);
 assert.deepEqual(errors,[]);
 await fs.writeFile(path.join(root,'.qa/browser/media-sync-result.json'),JSON.stringify({passed:true,metadata,sampleSHA256:linked.media.sha256,errors,checks:['real MP4 decode and range seeking','WAV cue pauses and continue','confirmation isolation','audience cue persistence','real time cue and single audio','manual captions','landscape swap and portrait','unlinked fallback','refresh pause','pause preserves actual position','hidden preview without audience does not rewind']},null,2));
 console.log('Media integration passed: '+JSON.stringify(metadata));
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();if(child)try{execFileSync(python,['-X','utf8','tools/stop.py','--data-dir',data],{cwd:root,windowsHide:true})}catch{child.kill()}});
