const {chromium}=require('playwright');
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.qa','browser');
const result={ok:false,checks:[],audits:[],errors:[]};let server,browser,page;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const mark=text=>{result.checks.push(text);console.log(text)};
const red='甲：很长的中文台词，保留换行和 emoji 🌸👩‍🎤。\n'.repeat(100);
const green='乙：同一段换色跨页，组合字符 e\u0301 与空格  不能丢。\n'.repeat(80);
const blocks=[{id:'long',kind:'text',role:'甲',text:red+green,runs:[{text:red,color:'#8C424E'},{text:green,color:'#3D6C61'}]},{id:'image',kind:'image',image_path:'/image.svg'},{id:'end',kind:'text',role:'乙',text:'图片后仍保留最后一段。'},{id:'short',kind:'text',role:'丙',text:'第二组只有这一句。'}];
const cues=[{id:'c1',at:20,label:'长组',block_ids:['long','image','end']},{id:'c2',at:25,label:'短组',block_ids:['short']}];
function wav(){const b=Buffer.alloc(44+480000);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);return b;}
const html=`<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/static/media-player.css"><style>body{margin:0;background:#272421;font-family:Arial,'Microsoft YaHei',sans-serif}#frame{margin:12px;width:432px;height:768px}.stage{width:1080px;height:1920px;transform:scale(.4);transform-origin:top left;--stage-scale:.4}.host{width:100%;height:100%}</style><div id="frame"><div class="stage portrait"><div class="host"></div></div></div><script src="/static/media-player.js"></script>`;
async function ready(){await sleep(100);await page.evaluate(()=>player.whenCaptionReady());}
async function create(options={}){await page.evaluate(async({blocks,cues,options})=>{window.player?.destroy();window.changes=[];window.player=new PiaMediaPlayer({container:document.querySelector('.host'),script:{blocks,media:{path:'/tone.wav',kind:'audio',duration:30,cues:options.cues??cues}},layout:{font_size:36,line_height:1.7,padding:40,...options.layout},preview:true,onChange:detail=>changes.push(detail)});await player.whenCaptionReady();},{blocks,cues,options});await page.waitForFunction(()=>player.media.readyState>=2);await ready();}
async function geometry(orientation,scale){await page.evaluate(({orientation,scale})=>{const w=orientation==='portrait'?1080:1920,h=orientation==='portrait'?1920:1080,stage=document.querySelector('.stage');stage.className='stage '+orientation;stage.style.cssText=`width:${w}px;height:${h}px;transform:scale(${scale});--stage-scale:${scale}`;document.querySelector('#frame').style.cssText=`width:${w*scale}px;height:${h*scale}px`;},{orientation,scale});await ready();}
async function audit(label,expected=blocks.slice(0,3)){
 const value=await page.evaluate(()=>{const result={pages:[],texts:{},ranges:{},colors:{},roles:{},images:0,overflow:[],index:player.captionPageIndex,count:player.captionPageCount,layout:player.root.dataset.captionLayout};for(const pg of player.root.querySelectorAll('.pia-media-caption-page')){const hidden=pg.hidden;pg.hidden=false;const content=[];if(pg.scrollHeight>pg.clientHeight+1)result.overflow.push(pg.dataset.captionPageIndex);for(const block of pg.querySelectorAll('[data-block-id]')){const id=block.dataset.blockId,text=block.querySelector('.pia-media-block-text');if(text){(result.texts[id]??=[]).push(text.textContent);(result.ranges[id]??=[]).push([+block.dataset.sourceStart,+block.dataset.sourceEnd]);(result.roles[id]??=[]).push(block.querySelector('.pia-media-role')?.textContent||'');for(const span of text.querySelectorAll('span'))(result.colors[id]??=[]).push({text:span.textContent,color:span.style.color});content.push([id,text.textContent]);}const image=block.querySelector('img');if(image){result.images++;const i=image.getBoundingClientRect(),p=pg.getBoundingClientRect();if(i.height<=0||i.bottom>p.bottom+1||i.right>p.right+1||Math.abs(i.width/i.height-image.naturalWidth/image.naturalHeight)>.02)result.overflow.push('image');content.push([id,'image']);}}result.pages.push(content);pg.hidden=hidden;}result.scroll=player.captionScroll.scrollHeight;result.height=player.captionScroll.clientHeight;return result;});
 assert.equal(value.layout,'pages',label);assert.deepEqual(value.overflow,[],label+' overflow');assert(value.scroll<=value.height+1,label+' no vertical scroll');
 for(const block of expected.filter(b=>b.kind==='text')){assert.equal(value.texts[block.id].join(''),block.text,label+' exact text');let end=0;for(const [start,next]of value.ranges[block.id]){assert.equal(start,end);end=next;}assert.equal(end,block.text.length);assert(value.roles[block.id].every(role=>role===(block.role||'')));}
 assert.equal(value.images,expected.filter(b=>b.kind==='image').length);
 if(value.colors.long){const merged=[];for(const run of value.colors.long){if(merged.at(-1)?.color===run.color)merged.at(-1).text+=run.text;else merged.push({...run})}assert.deepEqual(merged,[{text:red,color:'rgb(140, 66, 78)'},{text:green,color:'rgb(61, 108, 97)'}]);}
 result.audits.push({label,pages:value.count,images:value.images});return value;
}
(async()=>{
 await fs.mkdir(out,{recursive:true});server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(['/static/media-player.js','/static/media-player.css','/static/media-pagination.js'].includes(url.pathname)){res.setHeader('Content-Type',url.pathname.endsWith('.js')?'text/javascript':'text/css');res.end(await fs.readFile(path.join(root,url.pathname.slice(1))));}else if(url.pathname==='/tone.wav'){const b=wav();res.setHeader('Content-Type','audio/wav');res.setHeader('Content-Length',b.length);res.end(b);}else if(url.pathname==='/image.svg'||url.pathname==='/slow.svg'){if(url.pathname==='/slow.svg')await sleep(800);res.setHeader('Content-Type','image/svg+xml');res.end('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="1200"><rect width="400" height="1200" fill="#8c7756"/><text x="20" y="70" font-size="30">Original image</text></svg>');}else{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html);}}catch(e){res.statusCode=500;res.end(String(e));}});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(8907,'127.0.0.1',resolve)});
 browser=await chromium.launch({channel:'msedge',headless:true});page=await browser.newPage({viewport:{width:1800,height:1650}});page.on('pageerror',e=>result.errors.push(e.message));await page.goto('http://127.0.0.1:8907');
 await create();const portrait=await audit('portrait .4');assert(portrait.count>10);await page.evaluate(()=>{player.nextCaptionPage();player.nextCaptionPage()});
 const original=await page.evaluate(()=>player.getState());for(const scale of [.6,.8,.4]){await geometry('portrait',scale);const next=await audit('portrait '+scale);assert.equal(next.index,2);assert.deepEqual(next.pages,portrait.pages);}
 assert.deepEqual(await page.evaluate(()=>player.getState()),original);await page.locator('#frame').screenshot({path:path.join(out,'media-caption-pages-portrait.png')});mark('长中文/runs/role/图片完整；.4/.6/.8逐页文字与页数相同且当前位置不变');
 await page.evaluate(()=>player.nextCaption());await ready();assert.equal(await page.evaluate(()=>player.captionPageIndex),0);await audit('short group',[blocks.at(-1)]);
 await page.evaluate(()=>player.previousCaption());await ready();assert.equal(await page.evaluate(()=>player.captionPageIndex),0);
 await page.evaluate(()=>player.setState({position:3,caption_index:0,caption_page_index:3,cue_id:null},false,{remote:true}));await ready();assert.equal(await page.evaluate(()=>player.captionPageIndex),3);
 await page.evaluate(()=>player.setState({position:3,caption_index:0,cue_id:null},false,{remote:true}));assert.equal(await page.evaluate(()=>player.captionPageIndex),0);
 await page.evaluate(()=>player.setState({position:3,caption_index:0,caption_page_index:100000,cue_id:null},false,{remote:true}));assert.equal(await page.evaluate(()=>player.captionPageIndex),portrait.count-1);
 await page.evaluate(()=>{player.nextCaption();player.setState({position:3,caption_index:0,caption_page_index:4,cue_id:null},false,{remote:true})});await ready();assert.equal(await page.evaluate(()=>player.captionPageIndex),4);mark('换组归零、旧状态页0兼容、页恢复、clamp与快速切组异步恢复');
 await geometry('landscape',.6);const landscape=await audit('landscape .6');for(const scale of [.4,.8]){await geometry('landscape',scale);const next=await audit('landscape '+scale);assert.deepEqual(next.pages,landscape.pages);assert.equal(next.index,4);}await geometry('landscape',.6);await page.locator('#frame').screenshot({path:path.join(out,'media-caption-pages-landscape.png')});mark('横屏重排保留页，横屏各scale逐页相同');
 const before=await page.evaluate(()=>player.getState());await page.evaluate(()=>{changes=[];player.previousCaptionPage();player.nextCaptionPage()});assert.deepEqual(await page.evaluate(()=>player.getState()),before);assert.equal(await page.evaluate(()=>player.playing),false);assert.deepEqual(await page.evaluate(()=>changes.map(c=>c.reason)),['caption-page','caption-page']);
 await page.evaluate(async()=>{await player.play();changes=[];player.previousCaptionPage();player.nextCaptionPage()});assert(await page.evaluate(()=>player.playing));assert((await page.evaluate(()=>player.media.currentTime))>=before.position);assert.deepEqual(await page.evaluate(()=>changes.map(c=>c.reason)),['caption-page','caption-page']);await page.evaluate(()=>player.pause({remote:true}));mark('组内页只发caption-page，媒体暂停/播放意图及时间不被翻页改写');
 await create({layout:{media_caption_layout:'scroll'}});assert.equal(await page.locator('.pia-media-caption-page').count(),0);assert.equal(await page.locator('[data-block-id="long"] .pia-media-block-text').textContent(),red+green);const scroll=await page.evaluate(async()=>{player.captionScroll.scrollTop=250;const before=player.captionScroll.scrollTop;await player.setState(player.getState(),false,{remote:true});return{before,after:player.captionScroll.scrollTop,overflow:getComputedStyle(player.captionScroll).overflowY}});assert.equal(scroll.overflow,'auto');assert(scroll.before>0);assert.equal(scroll.after,scroll.before);
 await create({cues:[]});assert.equal(await page.evaluate(()=>player.groupCount),blocks.length);assert.deepEqual(await page.locator('.pia-media-block').evaluateAll(nodes=>[...new Set(nodes.map(n=>n.dataset.blockId))]),['long']);await page.evaluate(()=>player.nextCaption());await ready();assert.equal(await page.locator('.pia-media-block').getAttribute('data-block-id'),'image');assert.equal(await page.evaluate(()=>player.captionPageIndex),0);mark('scroll回退完整且远端同组更新不归顶；无cue每个文字/图片块单独一组');
 await create({layout:{font_size:64,line_height:2.2,padding:100}});await audit('large font');await page.evaluate(()=>{player.nextCaption();player.previousCaption();player.nextCaption()});await ready();await audit('rapid latest',[blocks.at(-1)]);
 const cleanup=await page.evaluate(async()=>{player.destroy();changes=[];player=new PiaMediaPlayer({container:document.querySelector('.host'),script:{blocks:[{id:'slow',kind:'image',image_path:'/slow.svg'}],media:{path:'/tone.wav',kind:'audio',cues:[]}},preview:true,onChange:c=>changes.push(c)});const start=performance.now(),pending=player.whenCaptionReady();player.destroy();await pending;return{ms:performance.now()-start,count:document.querySelectorAll('.pia-media-player').length}});assert(cleanup.ms<200);assert.equal(cleanup.count,0);await sleep(900);assert.equal(await page.evaluate(()=>changes.length),0);mark('字号重排与最新组胜出；destroy解除观察且立即结束就绪等待');assert.deepEqual(result.errors,[]);result.ok=true;
})().catch(async error=>{result.error=error.stack||String(error);console.error(error);process.exitCode=1;if(page)await page.screenshot({path:path.join(out,'media-caption-pages-failure.png'),fullPage:true}).catch(()=>{});}).finally(async()=>{await fs.mkdir(out,{recursive:true});await fs.writeFile(path.join(out,'media-caption-pages-result.json'),JSON.stringify(result,null,2));if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));console.log(JSON.stringify(result));});
