const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const base = process.argv[2] || 'http://127.0.0.1:8877';
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const lib = async() => (await context.request.get(base+'/api/library')).json();
  await page.goto(base+'/manage');
  await page.locator('#tab-categories').click();
  await page.locator('#new-category').click();
  await page.locator('#category-name').fill('功能验收临时分类');
  await page.locator('#category-form button[type=submit]').click();
  await page.locator('#category-dialog').waitFor({state:'hidden'});
  const category=(await lib()).categories.find(c=>c.name==='功能验收临时分类');assert(category);
  await page.locator('#new-category').click();
  await page.locator('#category-name').fill('功能验收临时分类');
  await page.locator('#category-form button[type=submit]').click();
  await page.waitForFunction(()=>document.querySelector('#category-error').textContent.length>0);
  assert(await page.locator('#category-dialog').isVisible());
  await page.locator('#category-dialog [data-close]').first().click();

  await page.locator('#new-script').click();
  await page.locator('#edit-title').fill('浏览器新增剧本');
  await page.locator('#edit-category').selectOption(category.id);
  await page.locator('#edit-author').fill('验收录入');
  await page.locator('#edit-synopsis').fill('用于检查编辑与安全显示。');
  await page.locator('#body-editor-details').evaluate(e=>e.open=true);
  await page.locator('#add-block').click();
  await page.locator('#body-editor textarea').last().fill('甲：测试台词 <img src=x onerror="alert(1)">');
  await page.locator('#script-form button[type=submit]').click();
  await page.locator('#script-dialog').waitFor({state:'hidden'});
  const script=(await lib()).scripts.find(s=>s.title==='浏览器新增剧本');assert(script);assert.equal(script.blocks.length,1);
  await page.goto(base+'/script/'+script.id);
  assert((await page.locator('#reader-body').innerText()).includes('<img src=x'));
  assert.equal(await page.locator('#reader-body img').count(),0);

  await page.goto(base+'/manage');
  await page.locator('#tab-categories').click();
  await page.locator(`[data-delete-category="${category.id}"]`).click();
  await page.locator('#confirm-dialog button[value=cancel]').click();
  assert((await lib()).categories.some(c=>c.id===category.id));
  await page.locator(`[data-delete-category="${category.id}"]`).click();
  await page.locator('#confirm-extra select').selectOption('uncategorized');
  await page.locator('#confirm-yes').click();
  await page.waitForFunction(id=>!document.querySelector(`[data-category-row="${id}"]`),category.id);
  const migrated=(await lib()).scripts.find(s=>s.id===script.id);assert.equal(migrated.category_id,'uncategorized');
  await page.locator('#tab-scripts').click();
  await page.locator(`[data-toggle-script="${script.id}"]`).click();
  await page.waitForTimeout(300);
  assert.equal((await lib()).scripts.find(s=>s.id===script.id).visible,false);

  await page.locator('#tab-backup').click();
  const downloadPromise=page.waitForEvent('download');await page.locator('a[href="/api/backup"]').click();
  const download=await downloadPromise;await fs.mkdir('.qa/browser',{recursive:true});await download.saveAs('.qa/browser/ui-backup.zip');
  const before=await lib();
  await context.request.patch(base+'/api/scripts/'+script.id,{data:{title:'等待恢复的修改'},headers:{'X-CSRF-Token':before.csrf_token}});
  await page.locator('#restore-file').setInputFiles('.qa/browser/ui-backup.zip');
  await page.locator('#restore-backup').click();await page.locator('#confirm-yes').click();
  await page.waitForFunction(()=>document.querySelector('#restore-status').textContent.includes('恢复完成'),null,{timeout:30000});
  assert.equal((await lib()).scripts.find(s=>s.id===script.id).title,'浏览器新增剧本');
  assert.deepEqual(errors,[]);
  await browser.close();console.log('Management browser acceptance passed: category validation, script editing, XSS text, cancel/delete/migrate, hide, download and restore.');
})().catch(e=>{console.error(e);process.exit(1)});
