'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs/promises');
const {spawn,execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),fan=path.join(root,'喜娃剧本粉丝编辑器'),python=path.join(root,'runtime','python.exe'),data=path.join(root,'.qa','fan-editor-'+Date.now()),output=path.join(root,'.qa','browser'),base='http://127.0.0.1:9042';
const result={passed:false,checks:[],errors:[],screenshots:[],data_dir:data},delay=ms=>new Promise(r=>setTimeout(r,ms));let browser,context,page,server,csrf='',release;
async function until(check,label){for(let i=0;i<180;i++){if(await check())return;await delay(80);}throw Error('Timed out: '+label);}
// Keep arbitrary user role keys intact across the browser automation bridge.
const draft=async()=>JSON.parse(await page.evaluate(()=>JSON.stringify(collect()))),row=id=>page.locator(`.block[data-block-id="${id}"]`),check=label=>result.checks.push(label);
async function stored(id){const response=await context.request.get(base+'/api/workspaces/'+id);assert(response.ok(),await response.text());return(await response.json()).script;}
async function save(){const response=page.waitForResponse(r=>r.request().method()==='PUT'&&new URL(r.url()).pathname.startsWith('/api/workspaces/'));await page.locator('#btnSave').click();const saved=await response;assert(saved.ok(),await saved.text());await until(async()=>!await page.locator('#btnSave').isDisabled(),'save UI unlocks');}
function fixtureFiles(){
  const code=String.raw`
import hashlib,io,json,sys,zipfile
from pathlib import Path
from PIL import Image
import script_package as package
from storage import encode
folder=Path(sys.argv[1]);folder.mkdir(parents=True,exist_ok=True)
out=io.BytesIO();Image.new('RGB',(160,90),(76,132,94)).save(out,format='PNG');image=out.getvalue();sha=hashlib.sha256(image).hexdigest();ref='/media/'+sha+'.png'
script={'id':'fan-ui-source','title':'粉丝适配专项','category_id':'fan-category','author':'原作者','synopsis':'浏览器真实操作','cast_note':'','notes':'','tags':[],'visible':True,'source_category':'原分类','source_pages':[1],
 'role_colors':{'甲':'#bb6633','预设':'#338855','constructor':'#884466','__proto__':'#229955'},
 'blocks':[{'id':'fan-text-original','kind':'text','role':'甲','text':'原稿多色台词','color':'#aa2244','runs':[{'text':'原稿','color':'#aa2244'},{'text':'多色台词','color':'#2288aa'}],'source_file':'source.pptx','source_page':1},
 {'id':'fan-text-keep','kind':'text','role':'甲','text':'保留未改多色','color':'#aa2244','runs':[{'text':'保留','color':'#aa2244'},{'text':'未改多色','color':'#2266bb'}],'source_file':'source.pptx','source_page':1},
 {'id':'fan-text-fallback','kind':'text','role':'乙','text':'没有集中默认色','color':'#112233','source_file':'source.pptx','source_page':1},
 {'id':'fan-text-untouched','kind':'text','role':'丙','text':'原多色一直保留','color':'#552244','runs':[{'text':'原多色','color':'#552244'},{'text':'一直保留','color':'#2288aa'}],'source_file':'source.pptx','source_page':1},
 {'id':'fan-image','kind':'image','text':'','image_path':ref,'source_file':'source.pptx','source_page':1}]}
script=package._normalize(script);content=encode(script).encode('utf-8');member='assets/'+sha+'.png';files={'script.json':{'size':len(content),'sha256':hashlib.sha256(content).hexdigest(),'mime':'application/json'},member:{'size':len(image),'sha256':sha,'mime':'image/png'}}
manifest={'format':package.FORMAT,'version':package.VERSION,'created_at':'2026-09-30T00:00:00+00:00','category_name':'测试分类','files':files,'resources':{ref:member}}
with zipfile.ZipFile(folder/'source.zip','w',zipfile.ZIP_DEFLATED)as archive:
 archive.writestr('script.json',content);archive.writestr(member,image);archive.writestr('manifest.json',encode(manifest))
(folder/'source.png').write_bytes(image)
replacement=io.BytesIO();Image.new('RGB',(100,160),(130,72,94)).save(replacement,format='PNG');(folder/'replacement.png').write_bytes(replacement.getvalue())
print(json.dumps(script,ensure_ascii=False))
`;
  return JSON.parse(execFileSync(python,['-X','utf8','-c',code,data],{cwd:root,windowsHide:true,encoding:'utf8'}));
}
(async()=>{
  await fs.mkdir(output,{recursive:true});let occupied=false;try{await fetch(base+'/api/health');occupied=true;}catch{}assert(!occupied,'QA port occupied');const source=fixtureFiles();
  server=spawn(python,['-X','utf8',path.join(fan,'fan_entry.py'),'--port','9042','--no-browser','--data-dir',data],{cwd:fan,windowsHide:true,stdio:'ignore'});
  await until(async()=>{try{return path.resolve((await(await fetch(base+'/api/health')).json()).data_dir)===data;}catch{return false;}},'isolated fan server');
  browser=await chromium.launch({channel:'msedge',headless:true});context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));await page.goto(base+'/');csrf=await page.locator('meta[name="csrf"]').getAttribute('content');
  await page.locator('#filePackage').setInputFiles(path.join(data,'source.zip'));await page.locator('#editorPanel').waitFor();await until(async()=>await page.locator('#blocks .block').count()===5,'fixture blocks');const wsid=await page.evaluate(()=>currentId);const before=await draft();assert.deepEqual(before.role_colors,source.role_colors);assert.deepEqual(before.blocks.find(b=>b.id==='fan-text-keep').runs,source.blocks.find(b=>b.id==='fan-text-keep').runs);assert.equal(await page.locator('#fan-role-options option[value="预设"]').count(),1);
  await page.locator('#btnAddText').click();const added=(await draft()).blocks.at(-1).id;await row(added).locator('.roleInput').fill('甲');assert.equal((await draft()).blocks.at(-1).color,'#bb6633');await row(added).locator('.colorInput').fill('#118899');await row(added).locator('.colorInput').dispatchEvent('input');assert.equal((await draft()).blocks.at(-1).color,'#118899');await row(added).locator('.textInput').fill('新增手动特殊色句子');
  await page.locator('#btnAddText').click();const fallback=(await draft()).blocks.at(-1).id;await row(fallback).locator('.roleInput').fill('乙');assert.equal((await draft()).blocks.at(-1).color,'#112233');await row(fallback).locator('.roleInput').fill('新角色');assert.equal((await draft()).blocks.at(-1).color,'#112233');await row(fallback).locator('.textInput').fill('新角色继续保持当前颜色');
  for(const[name,value]of[['constructor','#884466'],['__proto__','#229955']]){await row(fallback).locator('.roleInput').fill(name);assert.equal((await draft()).blocks.at(-1).color,value);}await row(fallback).locator('.roleInput').fill('乙');
  assert.deepEqual((await draft()).blocks.find(b=>b.id==='fan-text-keep').runs,before.blocks.find(b=>b.id==='fan-text-keep').runs);check('palette/default and first-role-colour fallback, preset options, manual exceptions, safe arbitrary role names');
  await row('fan-text-original').locator('.textInput').fill('输入后新增也不会丢词');await row('fan-text-original').locator('.roleInput').fill('乙');await row('fan-text-original').locator('.colorInput').fill('#663388');await row('fan-text-original').locator('.colorInput').dispatchEvent('input');await page.locator('#btnAddText').click();assert.equal(await row('fan-text-original').locator('.textInput').inputValue(),'输入后新增也不会丢词');assert.equal(await row('fan-text-original').locator('.roleInput').inputValue(),'乙');assert.equal(await row('fan-text-original').locator('.colorInput').inputValue(),'#663388');
  await row('fan-text-original').locator('[data-op="down"]').click();assert.equal(await row('fan-text-original').locator('.textInput').inputValue(),'输入后新增也不会丢词');await row('fan-text-original').locator('[data-op="up"]').click();assert.equal(await row('fan-text-original').locator('.textInput').inputValue(),'输入后新增也不会丢词');
  page.on('dialog',d=>d.accept());const removable=(await draft()).blocks.at(-1).id;await row(removable).locator('[data-op="del"]').click();assert.equal(await row('fan-text-original').locator('.textInput').inputValue(),'输入后新增也不会丢词');check('unsaved text/role/colour survive add, reorder and delete redraws');
  const keepId='fan-text-keep';await row(keepId).locator('.colorInput').fill('#778899');await row(keepId).locator('.colorInput').dispatchEvent('input');assert(!(await draft()).blocks.find(b=>b.id===keepId).runs,'explicit colour change clears old inline runs');
  // Another untouched original also remains in the fixture to verify that
  // saving a changed sentence does not alter its authored colour fragments.
  await save();assert.equal((await stored(wsid)).blocks.find(b=>b.id===keepId).color,'#778899');check('single-sentence colour changes are reflected in saved data instead of stale authored runs');
  const priorCount=(await draft()).blocks.length;let imageArrived=false;const held=new Promise(resolve=>{release=resolve;});await page.route('**/api/workspaces/'+wsid+'/images',async route=>{imageArrived=true;await held;await route.continue();});await page.locator('#fileImage').setInputFiles(path.join(data,'source.png'));await until(()=>imageArrived,'delayed image request');await row('fan-text-original').locator('.textInput').fill('上传期间编辑仍不丢词');release();release=null;await until(async()=>(await draft()).blocks.length===priorCount+1,'image joins draft');assert.equal(await row('fan-text-original').locator('.textInput').inputValue(),'上传期间编辑仍不丢词');await page.unroute('**/api/workspaces/'+wsid+'/images');
  const imageRef=(await draft()).blocks.find(b=>b.id==='fan-image').image_path;let replaceArrived=false;const replacing=new Promise(resolve=>{release=resolve;});await page.route('**/api/workspaces/'+wsid+'/images',async route=>{replaceArrived=true;await replacing;await route.continue();});const replacementResponse=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/images'));await row('fan-image').locator('.imgfile').setInputFiles(path.join(data,'replacement.png'));await until(()=>replaceArrived,'delayed replacement');await row('fan-image').locator('[data-op="up"]').click();await row('fan-text-original').locator('.textInput').fill('替换图片和排序期间也不丢词');release();release=null;const replacement=await(await replacementResponse).json();await until(async()=>(await draft()).blocks.find(b=>b.id==='fan-image').image_path===replacement.ref,'replacement uses stable block id');await page.unroute('**/api/workspaces/'+wsid+'/images');assert.notEqual(replacement.ref,imageRef);assert.equal(await row('fan-text-original').locator('.textInput').inputValue(),'替换图片和排序期间也不丢词');check('image addition/replacement callbacks retain ongoing text edits and stable block identity');
  await save();assert.equal((await stored(wsid)).blocks.find(b=>b.id==='fan-text-original').text,'替换图片和排序期间也不丢词');await row('fan-text-original').locator('.textInput').fill('保存之后继续编辑不回旧值');await page.locator('#btnAddText').click();assert.equal(await row('fan-text-original').locator('.textInput').inputValue(),'保存之后继续编辑不回旧值');await save();check('save response resynchronizes model; subsequent edit/redraw does not resurrect old text');
  const downloadEvent=page.waitForEvent('download');await page.locator('#btnExport').click();const downloaded=await downloadEvent,target=path.join(data,'roundtrip.zip');await downloaded.saveAs(target);const validate=String.raw`import json,sys,script_package as p
with open(sys.argv[1],'rb')as stream:
  with p._validated(stream)as pkg: print(json.dumps(pkg['script'],ensure_ascii=False))`;const exported=JSON.parse(execFileSync(python,['-X','utf8','-c',validate,target],{cwd:root,windowsHide:true,encoding:'utf8'}));assert.deepEqual(exported.role_colors,source.role_colors);const edited=exported.blocks.find(b=>b.id==='fan-text-original');assert.equal(edited.text,'保存之后继续编辑不回旧值');assert.equal(edited.color,'#663388');assert.equal(edited.source_file,'source.pptx');assert.equal(edited.source_page,1);assert.deepEqual(exported.blocks.find(b=>b.id==='fan-text-untouched').runs,source.blocks.find(b=>b.id==='fan-text-untouched').runs);check('actual downloaded ZIP is accepted by the current workbench validator with palette, colours, source, untouched runs and images');
  await page.screenshot({path:path.join(output,'fan-editor-normal.png')});result.screenshots.push(path.join(output,'fan-editor-normal.png'));
  for(const width of[960,390]){await page.setViewportSize({width,height:900});await page.evaluate(()=>document.querySelector('.editor-body').scrollTop=0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow at '+width);assert(await page.evaluate(()=>document.querySelector('.media-side').getBoundingClientRect().top>=document.querySelector('.editor-main').getBoundingClientRect().bottom),'stacked media must follow the full editor at '+width);await page.screenshot({path:path.join(output,'fan-editor-'+width+'.png')});result.screenshots.push(path.join(output,'fan-editor-'+width+'.png'));}check('normal, 960px and 390px layout have no outer horizontal overflow or stacked media overlap');assert.deepEqual(result.errors,[]);result.passed=true;
})().catch(error=>{result.error=error.stack;console.error(error);process.exitCode=1;}).finally(async()=>{if(release)release();if(page&&!page.isClosed()&&!result.passed){result.failed_draft=await draft().catch(()=>null);await page.screenshot({path:path.join(output,'fan-editor-failure.png'),fullPage:true}).catch(()=>{});}if(server){try{await fetch(base+'/api/shutdown',{method:'POST',headers:{'X-CSRF-Token':csrf}});for(let i=0;i<80&&server.exitCode===null;i++)await delay(100);}catch{}if(server.exitCode===null)server.kill();}if(browser)await browser.close();await fs.writeFile(path.join(output,'fan-editor-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,checks:result.checks,errors:result.errors}));});
