const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {spawn,execFileSync}=require('node:child_process');
const path=require('node:path');
const fs=require('node:fs/promises');
const root=path.resolve(__dirname,'..'),python=path.join(root,'runtime','python.exe');
const data=path.join(root,'.qa','background-ui-'+Date.now()),base='http://127.0.0.1:8894';
let browser,child;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(check,label){for(let i=0;i<120;i++){if(await check())return;await delay(100)}throw Error('Timed out: '+label)}
const stop=()=>execFileSync(python,['-X','utf8','tools/stop.py','--data-dir',data],{cwd:root,windowsHide:true});
(async()=>{
 await fs.mkdir(path.join(root,'.qa','browser'),{recursive:true});
 execFileSync(python,['-X','utf8','-c',"from PIL import Image; Image.new('RGB',(160,120),'#446677').save('.qa/browser/bg-fixture-a.png'); Image.new('RGB',(180,100),'#998844').save('.qa/browser/bg-fixture-b.png')"],{cwd:root,windowsHide:true});
 child=spawn(python,['-X','utf8','run.py','--no-browser','--port','8894','--data-dir',data],{cwd:root,windowsHide:true,stdio:'ignore'});
 await until(async()=>{try{return(await(await fetch(base+'/api/health')).json()).data_dir===data}catch{return false}},'server');
 browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050}}),errors=[];
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const assets=async()=> (await(await context.request.get(base+'/api/backgrounds')).json()).backgrounds;
 const lib=async()=> (await context.request.get(base+'/api/library')).json();
 await page.goto(base+'/manage');await page.locator('#tab-backgrounds').click();await page.locator('[data-background-id]').first().waitFor();
 const builtin=(await assets()).find(a=>a.builtin);assert(builtin);assert(await page.locator(`[data-delete-background="${builtin.id}"]`).isDisabled());
 await page.locator('#background-upload-file').setInputFiles({name:'伪造图片.png',mimeType:'image/png',buffer:Buffer.from('This is not an image')});
 await page.locator('#background-upload-name').fill('应被拒绝的文件');await page.locator('#background-upload-button').click();
 await until(async()=>!(await page.locator('#background-upload-button').isDisabled()),'invalid upload completed');assert(!(await assets()).some(a=>a.name==='应被拒绝的文件'));
 await page.locator('#background-upload-file').setInputFiles(path.join(root,'.qa','browser','bg-fixture-a.png'));
 await page.locator('#background-upload-name').fill('可管理的测试背景');await page.locator('#background-upload-button').click();
 await until(async()=> (await assets()).some(a=>a.name==='可管理的测试背景'),'upload');
 let asset=(await assets()).find(a=>a.name==='可管理的测试背景');assert.equal(asset.width,160);assert.equal(asset.height,120);assert(asset.can_delete);
 await page.locator(`[data-rename-background="${asset.id}"]`).click();await page.locator('#background-rename-name').fill('改名后的背景');
 await page.locator('#background-rename-form button[type=submit]').click();await page.locator('#background-rename-dialog').waitFor({state:'hidden'});
 await until(async()=> (await assets()).some(a=>a.name==='改名后的背景'),'rename');
 const category=(await lib()).categories.find(c=>!c.system&&c.id!=='uncategorized');assert(category);
 await page.locator('#tab-categories').click();await page.locator(`[data-edit-category="${category.id}"]`).click();
 await page.locator('#category-background').selectOption(asset.path);await page.locator('#category-form button[type=submit]').click();await page.locator('#category-dialog').waitFor({state:'hidden'});
 assert.equal((await lib()).categories.find(c=>c.id===category.id).background,asset.path);
 await page.locator('#tab-backgrounds').click();await until(async()=>await page.locator(`[data-delete-background="${asset.id}"]`).isDisabled(),'referenced background delete blocked');
 assert((await assets()).find(a=>a.id===asset.id).usage.categories.includes(category.name));
 await page.screenshot({path:path.join(root,'.qa','browser','background-library.png'),fullPage:true});
 await page.locator('#tab-categories').click();await page.locator(`[data-edit-category="${category.id}"]`).click();
 await page.locator('#category-background').selectOption('');await page.locator('#category-form button[type=submit]').click();await page.locator('#category-dialog').waitFor({state:'hidden'});
 assert.equal((await lib()).categories.find(c=>c.id===category.id).background,'');
 // Upload inside the editor selects a reusable asset, but cancelling preserves the category.
 await page.locator(`[data-edit-category="${category.id}"]`).click();await page.locator('#category-upload-file').setInputFiles(path.join(root,'.qa','browser','bg-fixture-b.png'));
 await page.locator('#category-upload-button').click();
 await until(async()=> (await page.locator('#category-background').inputValue()).startsWith('/media/'),'inline upload selected');
 const secondPath=await page.locator('#category-background').inputValue();
 await page.locator('#category-dialog [data-close]').first().click();assert.equal((await lib()).categories.find(c=>c.id===category.id).background,'');
 const second=(await assets()).find(a=>a.path===secondPath);assert(second&&second.can_delete);
 await page.locator('#tab-backgrounds').click();await page.locator(`[data-delete-background="${asset.id}"]`).click();await page.locator('#confirm-yes').click();
 await until(async()=> !(await assets()).some(a=>a.id===asset.id),'unused asset deleted');assert.equal((await context.request.get(base+asset.path)).status(),404);
 // Backup and restore preserve even unused background assets and their names.
 await page.locator('#tab-backup').click();const downloadEvent=page.waitForEvent('download');await page.locator('a[href="/api/backup"]').click();
 const download=await downloadEvent,backup=path.join(root,'.qa','browser','background-ui-backup.zip');await download.saveAs(backup);
 await page.locator('#tab-backgrounds').click();await page.locator(`[data-delete-background="${second.id}"]`).click();await page.locator('#confirm-yes').click();await until(async()=> !(await assets()).some(a=>a.id===second.id),'delete before restore');
 await page.locator('#tab-backup').click();await page.locator('#restore-file').setInputFiles(backup);await page.locator('#restore-backup').click();await page.locator('#confirm-yes').click();
 await page.waitForFunction(()=>document.querySelector('#restore-status').textContent.includes('恢复完成'));
 const restored=(await assets()).find(a=>a.id===second.id);assert(restored);assert.equal(restored.name,second.name);assert((await context.request.get(base+restored.path)).ok());
 await page.locator('#tab-backgrounds').click();await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:path.join(root,'.qa','browser','background-library-mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);
 await fs.writeFile(path.join(root,'.qa','browser','background-result.json'),JSON.stringify({passed:true,browserErrors:errors,checks:['builtin protection','real image validation','upload','rename','assign and clear category background','referenced delete guard','inline upload cancellation','unused delete','backup and restore unused asset metadata and pixels','mobile fit']},null,2));
 console.log('Background management acceptance passed: upload, rename, assign, clear, delete protection, inline upload, backup/restore and mobile.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();try{stop()}catch{}if(child&&child.exitCode===null)child.kill()});
