// Conflict/merge workflow checks against a new, isolated QA database only.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {spawn,execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),python=path.join(root,'runtime','python.exe'),port=8935,base='http://127.0.0.1:'+port;
const data=path.join(root,'.qa','import-conflicts-'+Date.now()),output=path.join(root,'.qa','browser');
fs.mkdirSync(output,{recursive:true});let child,browser,context,page,release;
const result={passed:false,checks:[],page_errors:[],data_dir:data,screenshots:[],import_errors:[]},delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(check,label){for(let i=0;i<220;i++){if(await check())return;await delay(80);}throw new Error('Timed out: '+label);}
async function get(route){const response=await context.request.get(base+route);assert(response.ok(),await response.text());return response.json();}
const library=()=>get('/api/library');
const categoryProperties=categories=>categories.map(({script_count,visible_count,...properties})=>properties);
async function api(route,method,payload){const token=(await library()).csrf_token,response=await context.request.fetch(base+route,{method,headers:{'X-CSRF-Token':token},data:payload});const value=await response.json();assert(response.ok(),JSON.stringify(value));return value;}
async function packageFile(id,name){const response=await context.request.get(base+'/api/scripts/'+id+'/export');assert(response.ok(),await response.text());const file=path.join(data,name+'.zip');fs.writeFileSync(file,await response.body());return file;}
function removeQaFixture(id){const code="from pathlib import Path; import sqlite3,sys; directory=Path(sys.argv[1]).resolve(); assert directory.parent.name=='.qa' and directory.name.startswith('import-conflicts-'); connection=sqlite3.connect(directory/'workbench.sqlite3'); connection.execute('DELETE FROM scripts WHERE id=?',(sys.argv[2],)); connection.commit(); connection.close()";execFileSync(python,['-X','utf8','-c',code,data,id],{cwd:root,windowsHide:true,stdio:'pipe'});}
async function openSingle(file){await page.locator('#open-script-package').click();await until(async()=>!await page.locator('#script-package-check').isDisabled(),'single categories');await page.locator('#script-package-file').setInputFiles(file);await page.locator('#script-package-check').click();await page.locator('#script-package-preview').waitFor();await until(async()=>!await page.locator('#script-package-check').isDisabled(),'single preview');}
async function closeSingle(){await page.locator('#script-package-dialog [data-package-close]').first().click();}
async function openMerge(file){await page.locator('#tab-backup').click();await page.locator('#open-library-merge').click();await until(async()=>!await page.locator('#library-merge-check').isDisabled(),'merge categories');await page.locator('#library-merge-file').setInputFiles(file);await page.locator('#library-merge-check').click();await page.locator('#library-merge-preview').waitFor();await until(async()=>!await page.locator('#library-merge-check').isDisabled(),'merge preview');}
async function screenshot(name){const file=path.join(output,name);await page.screenshot({path:file,fullPage:false});result.screenshots.push(file);}
(async()=>{try{
  let occupied=false;try{await fetch(base+'/api/health');occupied=true;}catch(_){}assert(!occupied,'Refusing to reuse occupied QA port');
  child=spawn(python,['-X','utf8','run.py','--no-browser','--port',String(port),'--data-dir',data],{cwd:root,windowsHide:true,stdio:'ignore'});
  await until(async()=>{try{return path.resolve((await(await fetch(base+'/api/health')).json()).data_dir)===data;}catch(_){return false;}},'QA server');
  browser=await chromium.launch({channel:'msedge',headless:true});context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});page=await context.newPage();page.on('pageerror',failure=>result.page_errors.push(failure.message));page.on('response',async response=>{if(response.url().endsWith('/import')&&response.status()>=400)result.import_errors.push({url:response.url(),status:response.status(),body:await response.json().catch(()=>null)});});
  const initial=await library(),categories=initial.categories,category=categories[0].id,secondCategory=categories[1].id,beforeState=await get('/api/state');
  const create=async(title,text)=>{const value=await api('/api/scripts','POST',{title,author:'验收作者',category_id:category,blocks:[{role:'甲',text,color:'#224466'}]});return value.script||value;};
  const original=await create('同名冲突验收','原稿台词'),duplicate=await create('完全相同验收','不要重复导入'),additional=await create('合并新增验收','新增台词');
  const originalFile=await packageFile(original.id,'conflict'),duplicateFile=await packageFile(duplicate.id,'duplicate'),newFile=await packageFile(additional.id,'new');
  const backupResponse=await context.request.get(base+'/api/backup');assert(backupResponse.ok());const backupFile=path.join(data,'full-backup.zip');fs.writeFileSync(backupFile,await backupResponse.body());
  await api('/api/scripts/'+original.id,'PATCH',{...original,author:'本地改稿作者',blocks:[{...original.blocks[0],text:'本地改稿台词'}]});
  const another=await create('同名冲突验收','另一个同名本');removeQaFixture(additional.id);
  await page.goto(base+'/manage');await page.waitForFunction(()=>window.wbScriptPackages?.refreshLibrary);
  let count=(await library()).scripts.length;
  await openSingle(duplicateFile);assert.match(await page.locator('#script-package-match-status').textContent(),/完全相同/);assert.equal(await page.locator('#script-package-action').inputValue(),'skip');assert.equal(await page.locator('#script-package-action option').count(),1);
  await page.locator('#script-package-confirm').click();await until(async()=>/已跳过/.test(await page.locator('#script-package-status').textContent()),'duplicate skipped');assert.equal((await library()).scripts.length,count);assert(await page.locator('#script-package-confirm').isDisabled());await closeSingle();
  result.checks.push('identical single-script import defaults to skip, offers no new/overwrite, and creates no duplicate');
  await openSingle(originalFile);assert.equal(await page.locator('#script-package-action').inputValue(),'skip');assert.equal(await page.locator('#script-package-target option').count(),3);
  await page.locator('#script-package-action').selectOption('overwrite');assert.equal(await page.locator('#script-package-target').inputValue(),'');assert(await page.locator('#script-package-confirm').isDisabled());
  await page.locator('#script-package-target').selectOption(original.id);assert.equal(await page.locator('#script-package-category').inputValue(),category);assert.match(await page.locator('#script-package-comparison').textContent(),/作者/);assert(await page.locator('#script-package-confirm').isDisabled());
  await page.locator('#script-package-overwrite-check').check();assert(!await page.locator('#script-package-confirm').isDisabled());
  const updated=(await library()).scripts.find(script=>script.id===original.id);await api('/api/scripts/'+original.id,'PATCH',{...updated,notes:'预览后又改了备注'});
  await page.locator('#script-package-confirm').click();await until(async()=>/已重新核对/.test(await page.locator('#script-package-error').textContent()),'stale single preview');
  assert.equal(await page.locator('#script-package-action').inputValue(),'overwrite');assert.equal(await page.locator('#script-package-target').inputValue(),original.id);assert(!await page.locator('#script-package-overwrite-check').isChecked());assert(await page.locator('#script-package-confirm').isDisabled());
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert((await page.locator('#script-package-dialog').boundingBox()).width<=390);await screenshot('import-conflicts-single-mobile.png');await closeSingle();await page.setViewportSize({width:1440,height:1000});
  assert.equal((await library()).scripts.find(script=>script.id===original.id).notes,'预览后又改了备注');assert.equal((await library()).scripts.length,count);assert.deepEqual(await get('/api/state'),beforeState);
  result.checks.push('same-title conflicts require a target and explicit overwrite acknowledgement; stale preview preserves target/action, resets acknowledgement, and cancel writes nothing');
  await openSingle(newFile);assert.equal(await page.locator('#script-package-action').inputValue(),'new');assert(await page.locator('#script-package-confirm').isDisabled());await page.locator('#script-package-category').selectOption(secondCategory);
  let imports=0,waiting=false;await page.route('**/api/script-packages/import',async route=>{imports++;waiting=true;await new Promise(resolve=>{release=resolve;});await route.continue();});
  await page.locator('#script-package-confirm').evaluate(button=>{button.click();button.click();});await until(()=>waiting,'single in flight');assert(await page.locator('#script-package-file').isDisabled());await page.keyboard.press('Escape');assert(await page.locator('#script-package-dialog').isVisible());release();release=null;
  await page.locator('#script-dialog').waitFor();await page.unroute('**/api/script-packages/import');assert.equal(imports,1);const imported=(await library()).scripts.find(script=>script.title===additional.title);assert(imported);assert.equal(imported.category_id,secondCategory);count++;
  await page.locator('#script-dialog [data-close="script-dialog"]').first().click();await openSingle(newFile);assert.match(await page.locator('#script-package-match-status').textContent(),/完全相同/);await closeSingle();removeQaFixture(imported.id);count--;
  result.checks.push('new single-script import requires category; rapid duplicate clicks submit once; repeating the same package is detected as identical');
  await openMerge(backupFile);const conflictRow=page.locator('.library-merge-item[data-source-id="'+original.id+'"]'),newRow=page.locator('.library-merge-item[data-source-id="'+additional.id+'"]');
  assert.equal(await conflictRow.locator('[data-merge-action]').inputValue(),'skip');assert.equal(await newRow.locator('[data-merge-action]').inputValue(),'new');assert.equal(await page.locator('[data-merge-action="'+duplicate.id+'"] option').count(),1);
  await page.locator('[data-source-category="'+category+'"]').selectOption(secondCategory);await conflictRow.locator('[data-merge-action]').selectOption('overwrite');assert.equal(await conflictRow.locator('[data-merge-target]').inputValue(),'');assert(await page.locator('#library-merge-confirm').isDisabled());
  await conflictRow.locator('[data-merge-target]').selectOption(original.id);assert.match(await page.locator('#library-merge-review').textContent(),/新增 1 篇.*覆盖 1 篇/);assert.match(await page.locator('#library-merge-review').textContent(),/作者/);await page.locator('#library-merge-overwrite-confirm').check();
  const latest=(await library()).scripts.find(script=>script.id===original.id);await api('/api/scripts/'+original.id,'PATCH',{...latest,notes:'合并预览后变动'});
  await page.locator('#library-merge-confirm').click();await until(async()=>/已重新核对/.test(await page.locator('#library-merge-error').textContent()),'merge stale preview');assert.equal(await page.locator('[data-source-category="'+category+'"]').inputValue(),secondCategory);assert.equal(await conflictRow.locator('[data-merge-target]').inputValue(),original.id);assert(!await page.locator('#library-merge-overwrite-confirm').isChecked());
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const bounds=await page.locator('#library-merge-dialog').boundingBox();assert(bounds.width<=390&&bounds.x>=0);assert(await page.locator('#library-merge-items').evaluate(element=>element.scrollHeight>element.clientHeight));await screenshot('import-conflicts-library-mobile.png');
  await page.locator('#library-merge-dialog [data-library-merge-close]').first().click();assert.equal((await library()).scripts.length,count);assert.equal((await library()).scripts.find(script=>script.id===original.id).notes,'合并预览后变动');assert.deepEqual(await get('/api/state'),beforeState);
  result.checks.push('backup merge classifies every script, only maps existing categories, preserves all choices after stale target, fits 390px with internal scrolling; cancel writes nothing');
  await page.setViewportSize({width:1440,height:1000});await openMerge(backupFile);await page.locator('[data-source-category="'+category+'"]').selectOption(secondCategory);await conflictRow.locator('[data-merge-action]').selectOption('overwrite');await conflictRow.locator('[data-merge-target]').selectOption(original.id);await page.locator('#library-merge-overwrite-confirm').check();
  let merges=0,mergeWaiting=false;await page.route('**/api/library-merge/import',async route=>{merges++;mergeWaiting=true;await new Promise(resolve=>{release=resolve;});await route.continue();});await page.locator('#library-merge-confirm').evaluate(button=>{button.click();button.click();});await until(()=>mergeWaiting,'merge in flight');assert(await page.locator('#library-merge-file').isDisabled());await page.keyboard.press('Escape');assert(await page.locator('#library-merge-dialog').isVisible());release();release=null;
  await until(async()=>/已完成：新增 1 篇，覆盖 1 篇/.test(await page.locator('#library-merge-status').textContent()),'merge complete');await page.unroute('**/api/library-merge/import');assert.equal(merges,1);assert(await page.locator('#library-merge-confirm').isDisabled());
  const after=await library();assert.equal(after.scripts.length,count+1);assert.equal(after.scripts.find(script=>script.title===additional.title).category_id,secondCategory);assert.equal(after.scripts.find(script=>script.id===original.id).author,original.author);assert.equal(after.scripts.find(script=>script.id===original.id).blocks[0].text,original.blocks[0].text);assert.deepEqual(after.scripts.find(script=>script.id===another.id),another);assert.deepEqual(categoryProperties(after.categories),categoryProperties(initial.categories));assert.deepEqual(await get('/api/state'),beforeState);
  await page.locator('#library-merge-dialog [data-library-merge-close]').first().click();await openMerge(backupFile);assert.equal(await page.locator('[data-merge-action="'+additional.id+'"] option').count(),1);assert.equal(await page.locator('[data-merge-action="'+original.id+'"] option').count(),1);assert.match(await page.locator('#library-merge-review').textContent(),/新增 0 篇.*覆盖 0 篇/);await page.locator('#library-merge-confirm').click();await until(async()=>/已完成：新增 0 篇，覆盖 0 篇/.test(await page.locator('#library-merge-status').textContent()),'repeat backup skip');assert.equal((await library()).scripts.length,count+1);assert.deepEqual(await get('/api/state'),beforeState);
  result.checks.push('atomic merge adds chosen new scripts, overwrites only the explicit target, preserves live state and other same-title script; re-import skips all identical scripts without duplication');
  await page.locator('#library-merge-dialog [data-library-merge-close]').first().click();
  const beforeOverwrite=(await library()).scripts.find(script=>script.id===original.id);await api('/api/scripts/'+original.id,'PATCH',{...beforeOverwrite,author:'单包覆盖前作者'});
  await page.locator('#tab-scripts').click();await openSingle(originalFile);await page.locator('#script-package-action').selectOption('overwrite');await page.locator('#script-package-target').selectOption(original.id);await page.locator('#script-package-overwrite-check').check();await page.locator('#script-package-confirm').click();await page.locator('#script-dialog').waitFor();
  assert.equal(await page.locator('#edit-script-id').inputValue(),original.id);assert.equal((await library()).scripts.find(script=>script.id===original.id).author,original.author);assert.equal((await library()).scripts.length,count+1);const history=await get('/api/scripts/'+original.id+'/history');assert((history.history || history).some(revision=>revision.script.author==='单包覆盖前作者'));assert.deepEqual(await get('/api/state'),beforeState);
  result.checks.push('single-package confirmed overwrite retains the target ID, saves its prior content to history, opens that editor, and never duplicates the script');
  await page.locator('#script-dialog [data-close="script-dialog"]').first().click();
  const repeatedFirst=await create('同批同名验收','同名版本一'),repeatedSecond=await create('同批同名验收','同名版本二'),repeatedBackup=await context.request.get(base+'/api/backup');const repeatedFile=path.join(data,'same-titles-backup.zip');assert(repeatedBackup.ok());fs.writeFileSync(repeatedFile,await repeatedBackup.body());removeQaFixture(repeatedFirst.id);removeQaFixture(repeatedSecond.id);
  await openMerge(repeatedFile);assert.equal(await page.locator('[data-merge-action="'+repeatedFirst.id+'"]').inputValue(),'new');assert.equal(await page.locator('[data-merge-action="'+repeatedSecond.id+'"]').inputValue(),'skip');await page.locator('[data-merge-action="'+repeatedSecond.id+'"]').selectOption('new');assert(await page.locator('#library-merge-confirm').isDisabled());assert.match(await page.locator('#library-merge-review').textContent(),/多篇同名条目选择了新增/);await page.locator('#library-merge-dialog [data-library-merge-close]').first().click();
  result.checks.push('two same-title scripts absent locally default to only one new; selecting both new is blocked before any writes');
  assert.deepEqual(result.page_errors,[]);result.passed=true;
}catch(failure){result.error=failure.stack;process.exitCode=1;if(page)result.ui_failure=await page.evaluate(()=>({single:document.querySelector('#script-package-error')?.textContent,merge:document.querySelector('#library-merge-error')?.textContent,status:document.querySelector('#library-merge-status')?.textContent})).catch(()=>null);}
finally{release?.();if(browser)await browser.close();if(child){try{execFileSync(python,['-X','utf8','tools/stop.py','--data-dir',data],{cwd:root,windowsHide:true,stdio:'ignore'});}catch(_){}child.kill();}fs.writeFileSync(path.join(output,'import-conflicts-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}
})();
