'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs/promises');
const {spawn,execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),python=path.join(root,'runtime','python.exe'),data=path.join(root,'.qa','editor-tools-'+Date.now()),base='http://127.0.0.1:8938',output=path.join(root,'.qa','browser');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms)),result={passed:false,checks:[],errors:[],data_dir:data};
let server,browser,context,page,release;
async function until(check,label){for(let i=0;i<180;i++){if(await check())return;await delay(80);}throw Error('Timed out: '+label);}
async function get(endpoint){const response=await context.request.get(base+endpoint);assert(response.ok(),await response.text());return response.json();}
async function send(endpoint,payload,method='POST'){const response=await context.request.fetch(base+endpoint,{method,headers:{'X-CSRF-Token':(await get('/api/library')).csrf_token},data:payload});assert(response.ok(),await response.text());return response.json();}
const draft=()=>page.evaluate(()=>window.piaEditor.getFullDraft()),check=label=>result.checks.push(label);
async function open(id){await page.locator(`[data-edit-script="${id}"]`).click();await page.locator('#script-dialog').waitFor();await page.locator('#body-editor-details').evaluate(node=>{node.open=true;});}
async function close(){await page.locator('#script-dialog [data-close="script-dialog"]').first().click();await page.locator('#script-dialog').waitFor({state:'hidden'});}
async function accept(){await page.locator('#confirm-dialog').waitFor();await page.locator('#confirm-yes').click();await page.locator('#confirm-dialog').waitFor({state:'hidden'});}
async function save(){await page.locator('#script-form button[type="submit"]').click();await page.locator('#script-dialog').waitFor({state:'hidden'});}
const roles=()=>page.locator('#editor-role-panel').evaluate(node=>{node.open=true;});
const row=id=>page.locator(`.body-editor-row[data-block-id="${id}"]`);
async function flush(){return page.evaluate(()=>window.piaEditorTools.flush());}
(async()=>{
  await fs.mkdir(output,{recursive:true});let occupied=false;try{await fetch(base+'/api/health');occupied=true;}catch{}assert(!occupied,'QA port is already occupied');
  server=spawn(python,['-X','utf8','run.py','--no-browser','--port','8938','--data-dir',data],{cwd:root,windowsHide:true,stdio:'ignore'});
  await until(async()=>{try{return path.resolve((await(await fetch(base+'/api/health')).json()).data_dir)===data;}catch{return false;}},'isolated service');
  browser=await chromium.launch({channel:'msedge',headless:true});context=await browser.newContext({viewport:{width:1500,height:1080}});page=await context.newPage();page.on('pageerror',error=>result.errors.push(error.message));
  const library=await get('/api/library');
  const fixture=await send('/api/scripts',{title:'编辑保护专项',category_id:library.categories[0].id,author:'原作者',role_colors:{甲:'#aa2244',预设角色:'#227755'},blocks:[
    {id:'qa-editor-a',kind:'text',role:'甲',text:'保留多色原文',color:'#aa2244',runs:[{text:'保留',color:'#aa2244'},{text:'多色原文',color:'#2288bb'}]},
    {id:'qa-editor-b',kind:'text',role:'甲',text:'手工特殊色',color:'#335588'},
    {id:'qa-editor-c',kind:'text',role:'乙',text:'没有默认色的角色',color:'#446688'}]});
  await send('/api/apply',{mode:'script',script_id:fixture.id,orientation:'portrait'});const frozen=await get('/api/state');
  await page.goto(base+'/manage');await page.waitForFunction(()=>!!window.piaEditorTools);assert(await page.evaluate(()=>window.piaEditorTools.ready));await open(fixture.id);await roles();
  const original=await draft();assert.deepEqual(original.role_colors,fixture.role_colors);assert(await page.locator('#script-role-options option[value="预设角色"]').count());
  await page.locator('[data-role-default="甲"]').fill('#bb6633');await page.locator('[data-role-default="甲"]').dispatchEvent('change');
  assert.deepEqual((await draft()).blocks,original.blocks,'changing role default must preserve all authored sentence runs');
  await page.locator('#add-block').click();const added=(await draft()).blocks.at(-1).id;await row(added).locator('textarea').fill('新增句');await row(added).locator('[data-block-role]').fill('甲');assert.equal((await draft()).blocks.at(-1).color,'#bb6633');
  await row(added).locator('[data-block-color]').fill('#118899');await row(added).locator('[data-block-color]').dispatchEvent('input');assert.equal((await draft()).blocks.at(-1).color,'#118899');
  check('role defaults, preset role candidates, authored inline runs and per-sentence exceptions');
  const preUnify=await draft();await page.locator('[data-role-unify="甲"]').click();await page.locator('#confirm-dialog').waitFor();assert((await page.locator('#confirm-title').textContent()).includes('3 句'));await accept();await until(async()=>(await draft()).blocks.filter(b=>b.role==='甲').every(b=>b.color==='#bb6633'&&b.runs.length===1),'bulk role colour completes');
  await page.locator('#editor-undo').click();assert.deepEqual(await draft(),preUnify);await page.locator('#editor-redo').click();assert((await draft()).blocks.filter(b=>b.role==='甲').every(b=>b.color==='#bb6633'));await page.locator('#editor-undo').click();check('explicit bulk colour confirmation and lossless undo/redo');
  await page.locator('#edit-author').fill('修改作者');await page.locator('#edit-author').press('Control+z');assert.equal((await draft()).author,'原作者');await page.locator('#edit-author').press('Control+y');assert.equal((await draft()).author,'修改作者');
  const beforeImport=await draft();await page.evaluate(()=>window.piaEditor.applyImport({session_id:window.piaEditor.getDraft().session_id,mode:'append',candidate:{blocks:[{kind:'text',role:'乙',text:'导入句',color:'#446688'}]}}));assert.equal((await draft()).blocks.length,beforeImport.blocks.length+1);await page.locator('#editor-undo').click();assert.deepEqual(await draft(),beforeImport);
  const first=(await draft()).blocks[0].id;await row(first).locator('[data-block-move][data-delta="1"]').click();assert.notEqual((await draft()).blocks[0].id,first);await page.locator('#editor-undo').click();assert.equal((await draft()).blocks[0].id,first);
  check('metadata keyboard shortcuts, import and block reorder are undoable');
  const protectedDraft=await draft(),savedKey=(await flush()).storageKey;assert(savedKey.includes(encodeURIComponent(data)));assert(await page.evaluate(key=>!!localStorage.getItem(key),savedKey));
  await page.reload();await page.waitForFunction(()=>!!window.piaEditorTools);await page.evaluate(()=>window.piaEditorTools.ready);await open(fixture.id);await page.locator('#editor-recovery').waitFor();assert(await page.locator('#edit-title').isDisabled(),'pending recovery must guard against silently replacing the old draft');
  await page.locator('#editor-recover').click();await page.locator('#editor-recovery').waitFor({state:'hidden'});assert.deepEqual(await draft(),protectedDraft);assert.equal((await get('/api/library')).scripts.find(s=>s.id===fixture.id).author,'原作者');assert.deepEqual(await get('/api/state'),frozen);
  await close();await open(fixture.id);await page.locator('#editor-recovery').waitFor();await page.locator('#editor-recover').click();assert.deepEqual(await draft(),protectedDraft);check('reload/cancel recover all metadata, roles, blocks and preserve database/live state');
  await save();assert.equal(await page.evaluate(key=>localStorage.getItem(key),savedKey),null);const persisted=(await get('/api/library')).scripts.find(s=>s.id===fixture.id);assert.deepEqual(persisted.role_colors,{甲:'#bb6633',预设角色:'#227755'});assert.equal(persisted.blocks.find(b=>b.id===added).color,'#118899');
  await open(fixture.id);assert(await page.locator('#editor-undo').isDisabled());await page.locator('#edit-synopsis').fill('旧本机草稿');await flush();await close();await send('/api/scripts/'+fixture.id,{author:'另一个窗口正式保存'},'PATCH');await page.reload();await page.waitForFunction(()=>!!window.piaEditorTools);await page.evaluate(()=>window.piaEditorTools.ready);await open(fixture.id);assert((await page.locator('#editor-recovery-message').textContent()).includes('已经变化'));await page.locator('#editor-recover').click();await accept();await page.locator('#editor-recovery').waitFor({state:'hidden'});assert.equal((await draft()).synopsis,'旧本机草稿');assert.equal((await draft()).author,'修改作者');check('successful save clears draft, new undo history starts clean, changed saved version requires explicit recovery');
  await page.locator('#editor-history-panel').evaluate(node=>{node.open=true;});await until(async()=>await page.locator('.editor-history-entry').count()>=2,'historical versions');await page.locator('.editor-history-entry').last().click();await page.locator('#editor-history-diff').waitFor();assert((await page.locator('#editor-history-diff').textContent()).includes('对比'));await page.locator('#editor-history-restore').click();await accept();await until(async()=>await page.locator('#editor-recovery').isVisible(),'unsaved draft preserved after formal history restoration');assert((await page.locator('#editor-recovery-message').textContent()).includes('已经变化'));
  const restored=(await get('/api/library')).scripts.find(s=>s.id===fixture.id);assert.equal(restored.author,'原作者');assert.deepEqual(restored.role_colors,fixture.role_colors);const withoutOriginal=blocks=>blocks.map(({original_text,...block})=>block);assert.deepEqual(withoutOriginal(restored.blocks),withoutOriginal(fixture.blocks));assert.deepEqual(await get('/api/state'),frozen);assert((await get('/api/scripts/'+fixture.id+'/history')).history.some(h=>h.script.author==='另一个窗口正式保存'));
  await page.locator('#editor-discard').click();await accept();await page.locator('#editor-recovery').waitFor({state:'hidden'});check('visual version diff and formal restoration archive current version and retain unsaved local draft/live snapshot');
  await page.locator('#edit-author').fill('保存并发锁测试');let arrived=false;const held=new Promise(resolve=>{release=resolve;});await page.route('**/api/scripts/'+fixture.id,async route=>{if(route.request().method()==='PATCH'){arrived=true;await held;}await route.continue();});await page.locator('#script-form button[type="submit"]').click();await until(()=>arrived,'save request reaches lock');assert(await page.locator('#editor-undo').isDisabled());assert(await page.locator('#edit-author').isDisabled());assert(await page.locator('#script-dialog [data-close="script-dialog"]').first().isDisabled());await page.keyboard.press('Escape');assert(await page.locator('#script-dialog').isVisible());release();release=null;await page.locator('#script-dialog').waitFor({state:'hidden'});await page.unroute('**/api/scripts/'+fixture.id);check('asynchronous save locks editing, undo, close and Escape until completion');
  await open(fixture.id);await roles();const beforeImage=await draft(),sourceImage=library.scripts.flatMap(s=>s.blocks).find(b=>b.kind==='image');assert(sourceImage,'QA seed contains a usable image');const imageResponse=await context.request.get(base+sourceImage.image_path);assert(imageResponse.ok());let uploadArrived=false;const uploadHeld=new Promise(resolve=>{release=resolve;});await page.route('**/api/script-images',async route=>{uploadArrived=true;await uploadHeld;await route.continue();});const chooserEvent=page.waitForEvent('filechooser');await page.locator('#add-image-block').click();await(await chooserEvent).setFiles({name:'草稿撤销测试'+path.extname(sourceImage.image_path),mimeType:'image/jpeg',buffer:await imageResponse.body()});await until(()=>uploadArrived,'image upload locked');assert(await page.locator('#editor-undo').isDisabled());assert(await page.locator('#edit-title').isDisabled());assert(await page.locator('#script-dialog [data-close="script-dialog"]').first().isDisabled());release();release=null;await until(async()=>(await draft()).blocks.length===beforeImage.blocks.length+1,'uploaded image draft');await until(async()=>!await page.locator('#editor-undo').isDisabled(),'upload finishes');const afterImage=await draft();await page.locator('#editor-undo').click();assert.deepEqual(await draft(),beforeImage);await page.locator('#editor-redo').click();assert.deepEqual(await draft(),afterImage);await page.unroute('**/api/script-images');check('image upload busy locks, image asset snapshot undo/redo preserve metadata');
  await page.locator('#editor-undo').click();const imeBlock=(await draft()).blocks[0].id,imeBefore=(await draft()).blocks[0].text;await row(imeBlock).locator('textarea').evaluate(node=>{node.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));node.value='中文输入法新内容';node.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,inputType:'insertCompositionText'}));node.dispatchEvent(new KeyboardEvent('keydown',{bubbles:true,ctrlKey:true,key:'z',isComposing:true}));});assert.equal((await draft()).blocks[0].text,'中文输入法新内容');await row(imeBlock).locator('textarea').dispatchEvent('compositionend');await page.locator('#editor-undo').click();assert.equal((await draft()).blocks[0].text,imeBefore);await page.locator('#editor-redo').click();assert.equal((await draft()).blocks[0].text,'中文输入法新内容');check('IME commits are one logical undo step and composing shortcuts do not consume input');
  await page.evaluate(()=>{window.originalDraftSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Quota exceeded','QuotaExceededError');};});await page.locator('#edit-notes').fill('配额满时仍保护当前窗口草稿');await flush();assert((await page.locator('#editor-draft-status').textContent()).includes('未写入成功'));await close();await open(fixture.id);await page.locator('#editor-recovery').waitFor();assert((await page.locator('#editor-recovery-message').textContent()).includes('当前窗口暂存'));await page.locator('#editor-recover').click();assert.equal((await draft()).notes,'配额满时仍保护当前窗口草稿');await page.evaluate(()=>{Storage.prototype.setItem=window.originalDraftSetItem;delete window.originalDraftSetItem;});await flush();await save();check('storage quota error is explicit, temporary same-window recovery works, formal save stays usable');
  await open(fixture.id);const corruptKey=(await flush()).storageKey;await close();await page.evaluate(key=>localStorage.setItem(key,'{bad draft'),corruptKey);await page.reload();await page.waitForFunction(()=>!!window.piaEditorTools);await page.evaluate(()=>window.piaEditorTools.ready);await open(fixture.id);assert((await page.locator('#editor-recovery-message').textContent()).includes('无法读取'));assert(await page.locator('#editor-recover').isDisabled());assert.equal(await page.evaluate(key=>localStorage.getItem(key),corruptKey),'{bad draft');await page.locator('#editor-discard').click();await accept();await page.locator('#editor-recovery').waitFor({state:'hidden'});assert(!await page.locator('#edit-title').isDisabled());await close();check('malformed persisted draft is retained and explicitly discarded, never silently overwritten');
  const authored=library.scripts.find(s=>s.blocks.some(b=>b.kind!=='image'&&b.runs?.length>1));if(authored){await open(authored.id);const authoredBefore=await draft();await page.evaluate(role=>window.piaEditor.setRoleColor(role||'原文角色','#123456'),authored.blocks.find(b=>b.kind!=='image'&&b.runs?.length>1).role);assert.deepEqual((await draft()).blocks,authoredBefore.blocks);await close();check('real seeded multicolour original survives default-role edits');}
  await page.locator('#new-script').click();await page.locator('#body-editor-details').evaluate(node=>{node.open=true;});await roles();for(const [role,value]of[['constructor','#226644'],['__proto__','#663388']]){await page.locator('#editor-new-role').fill(role);await page.locator('#editor-new-role-color').fill(value);await page.locator('#editor-add-role').click();await page.locator('#add-block').click();await page.locator('#body-editor [data-block-role]').last().fill(role);assert.equal((await draft()).blocks.at(-1).color,value);assert(await page.evaluate(role=>Object.hasOwn(window.piaEditor.getFullDraft().role_colors,role),role));}check('free role names constructor and __proto__ safely retain real own colours');
  await page.setViewportSize({width:390,height:844});await page.locator('#editor-role-panel').scrollIntoViewIfNeeded();assert(await page.locator('#script-dialog').evaluate(node=>node.scrollWidth<=node.clientWidth+2));await page.screenshot({path:path.join(output,'editor-tools-narrow.png')});check('390px editor role panel and toolbar stay within the dialog');
  assert.deepEqual(result.errors,[]);assert.deepEqual(await get('/api/state'),frozen);result.passed=true;
})().catch(error=>{result.error=error.stack;console.error(error);process.exitCode=1;}).finally(async()=>{
  if(release)release();if(page&&!page.isClosed()&&!result.passed){result.failed_draft=await draft().catch(()=>null);result.role_status=await page.locator('#editor-role-status').textContent().catch(()=>null);result.image_status=await page.locator('#script-image-status').textContent().catch(()=>null);await page.screenshot({path:path.join(output,'editor-tools-failure.png'),fullPage:true}).catch(()=>{});}
  if(browser)await browser.close();if(server){try{result.stop=execFileSync(python,['-X','utf8','tools/stop.py','--data-dir',data],{cwd:root,windowsHide:true,encoding:'utf8',timeout:20000});}catch(error){result.stop_error=String(error);result.passed=false;if(server.exitCode===null)server.kill();}}
  await fs.writeFile(path.join(output,'editor-tools-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,checks:result.checks,errors:result.errors}));
});
